/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 5ea17e8d35d1e58061bfb1875e589cd4)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat" | "MessageStorage";
	}
	interface Env {
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		MessageStorage: DurableObjectNamespace<import("./src/server").MessageStorage>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
